development:
  adapter: postgresql
  encoding: unicode
  database: qwizzy
  host: localhost
  username: andylee
  password: 
test:
  adapter: postgresql
  encoding: unicode
  database: qwizzy_test
  host: localhost
  pool: 5
  username: andylee
  password: password
production:
  adapter: postgresql
  encoding: unicode
  database: qwizzy_production
  pool: 25
  username: postgres
  password: password​